name: Deploy to GitHub Pages

on:
  push:
    branches: [ interopen-hack ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build IG
        run: |
          ./_genonce.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets._GH_TOKEN }}
          publish_dir: ./output
